(function(g){var window=this;var soa=function(a){if(!a.Ia||!a.Ia.annotations)return null;a=g.p(a.Ia.annotations);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.playerAnnotationsExpandedRenderer&&b.playerAnnotationsExpandedRenderer.featuredChannel)return b.playerAnnotationsExpandedRenderer;return null},u1=function(a){a.u||(a.u=new g.rn,g.B(a,a.u));
return a.u},v1=function(a){a.R("cardstatechange",g.dL(a)&&g.eL(a)?1:0)},toa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Xj&&a.dataset){if(g.gc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.bd("pollChoiceIndex"))},uoa=function(a){return Math.pow(a,3)},voa=function(a){return 3*a*a-2*a*a*a},w1=function(a,b){(0,g.y)(b,function(c){c={csn:a,
ve:g.DA(c),eventType:4};var d={rj:void 0,Eh:a};"UNDEFINED_CSN"==a?g.OA("visualElementShown",c,d):g.qr("visualElementShown",c,g.vr,d)})},x1=function(a,b){(0,g.y)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.DA(c),eventType:d?16:8};d={rj:void 0,Eh:a,VC:d};"UNDEFINED_CSN"==a?g.OA("visualElementHidden",c,d):g.qr("visualElementHidden",c,g.vr,d)})},A1=function(a){a=g.Na(a);
delete y1[a];g.Wb(y1)&&z1&&z1.stop()},B1=function(){z1||(z1=new g.J(function(){woa()},20));
var a=z1;a.isActive()||a.start()},woa=function(){var a=(0,g.E)();
g.Ib(y1,function(b){C1(b,a)});
g.Wb(y1)||B1()},D1=function(a,b,c,d){g.fn.call(this);
if(!g.Ia(a)||!g.Ia(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.J=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.D=null},C1=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.D);a.D=b;E1(a,a.progress);1==a.progress?(a.o=0,A1(a),a.Zc(),a.A()):1==a.o&&a.Gr()},E1=function(a,b){g.Ka(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.J[c]-a.w[c])*b+a.w[c]},F1=function(a,b){g.fe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},G1=function(a,b,c,d,e){D1.call(this,b,c,d,e);
this.element=a},H1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
G1.call(this,a,b,c,d,e)},I1=function(a){g.A.call(this);
this.u=a||window;this.o=[]},xoa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.fr(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},J1=function(a){return a.baseUrl||null},yoa=function(a,b,c){function d(na){var Ha=na.hovercardButton;
if(!Ha)return null;Ha=Ha.subscribeButtonRenderer;if(!Ha)return null;var Tb=f(Ha.unsubscribedButtonText),Wc=f(Ha.subscribedButtonText);if(Ha.subscribed){var Lf=f(Ha.subscriberCountWithUnsubscribeText);var Te=f(Ha.subscriberCountText)}else Lf=f(Ha.subscriberCountText),Te=f(Ha.subscriberCountWithSubscribeText);var Yd=null;return na.signinEndpoint&&(Yd=g.Qb(na,"signinEndpoint","webNavigationEndpointData","url"),!Yd)?null:Tb&&(Wc||Yd)?{subscribed:Ha.subscribed,subscribeText:Tb,subscribeCount:Lf,unsubscribeText:Wc,
unsubscribeCount:Te,enabled:Ha.enabled,signinUrl:Yd,classic:na.useClassicSubscribeButton}:null}
function e(na){if(na){var Ha=[],Tb=na.videoId;Tb&&Ha.push("v="+Tb);(Tb=na.playlistId)&&Ha.push("list="+Tb);(na=na.startTimeSeconds)&&Ha.push("t="+na);return"/watch?"+Ha.join("&")}}
function f(na){if(!na)return null;var Ha=na.simpleText;return Ha?Ha:na.runs?(0,g.H)(na.runs,function(Tb){return Tb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,z=null,C=!1,D=null,G=null,K=null,F=null,M=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Qb(l,"browseEndpoint","browseId"))z=C,m="/channel/"+z;n=!1;q="new";(C=!!b.isSubscribe)?D=d(b):G=f(b.subscribersText)}else"WEBSITE"==
k?((K=g.Qb(l,"urlEndpoint","url"))&&(m=K),n=!0,q="new",K=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=g.Qb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Qb(b,"title","accessibility","accessibilityData","label");var ka=b.endpoint?b.endpoint.clickTrackingParams:null;return{id:"element-"+c,type:k,title:f(b.title),metadata:b.metadata?f(b.metadata):"",callToAction:f(b.callToAction),Ru:b.image,iconUrl:K,
left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:D,subscribersText:G,isSubscribe:C,targetUrl:m,xE:n,Gb:{itct:ka},xN:q,ij:a?a:null,BE:b.isPlaceholder,impressionUrls:(0,g.H)(b.impressionUrls||[],J1),nE:(0,g.H)(b.hovercardShowUrls||[],J1),clickUrls:(0,g.H)(l.loggingUrls||[],J1),visualElement:g.CA(b.trackingParams),productPrice:F,
additionalFeesText:M}},K1=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.H)(a.impressionUrls||[],J1);a.trackingParams&&(c.visualElement=g.CA(a.trackingParams));var d=(0,g.H)(a.elements||[],function(e,f){return yoa(b,e,f)});
c.elements=(0,g.Rd)(d,function(e){return!!e});
return c},L1=function(a){g.EQ.call(this,a);
this.A=this.u=null;this.o={};this.D={};this.C=this.w=null;this.H=[];a=a.O();this.J=g.Ox(a)||g.Qx(a);this.S=!0;this.G=0;this.B=new g.R(this);g.B(this,this.B);this.B.M(this.player,g.kF("creatorendscreen"),this.kF);this.B.M(this.player,"crx_creatorendscreen",this.lF);this.B.M(this.player,"resize",this.Uw);this.B.M(window,"focus",this.sM);this.load();var b=g.Ld("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ce(this,function(){g.Qd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},M1=function(a){return a.player.getVideoData().Zb?"current":a.J?"new":"current"},N1=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},O1=function(a,b,c){c=void 0===c?!0:c;
g.YR(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.D={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&zoa(a);c=[];d=new g.hF(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.w=new g.X({F:"div",I:"ytp-ce-shadow"}),g.oL(a.player,a.w.element,4),a.C=new g.SM(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Aoa(a,e);a.o[e.id]=f;a.D[e.id]=e;g.oL(a.player,f.element,4);var k=new g.hF(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Boa(a,f,e)}g.kL(a.player,c);
a.Uw()}},zoa=function(a){var b=g.XA(),c=g.YA();
c&&b&&a.u.visualElement&&g.PA(c,b,[a.u.visualElement],void 0)},Aoa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={F:"div",X:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":b.ij||"","aria-hidden":"true"},K:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",N:P1(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",N:{href:Q1(a,b.targetUrl),tabindex:"-1"},K:[{F:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.kn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.X(c);break;case "PLAYLIST":c={F:"div",X:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":b.ij||"","aria-hidden":"true"},K:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",N:P1(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",N:{href:Q1(a,b.targetUrl),tabindex:"-1"},K:[{F:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.kn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-playlist-count",K:[{F:"div",
I:"ytp-ce-playlist-icon"},{F:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.X(c);break;case "CHANNEL":c={F:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":b.ij||"","aria-hidden":"true"},K:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",K:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
K:[{F:"div",I:"ytp-ce-expanding-overlay-body",K:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{F:"a",X:["ytp-ce-channel-title","ytp-ce-link"],N:{href:Q1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.kn(b.title||"")},W:b.title},b.subscribeButton?{F:"div",I:"ytp-ce-subscribe-container",K:[{F:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{F:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",N:P1(b)}]};c=new g.X(c);var d=g.xd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.L(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Gb.itct}else e="endscreen",f=null;e=new g.jR(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={F:"div",X:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":b.ij||"","aria-hidden":"true"},K:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",K:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",K:[{F:"div",I:"ytp-ce-expanding-overlay-body",
K:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{F:"div",I:"ytp-ce-website-title",N:{dir:g.kn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-website-metadata",W:b.metadata},{F:"a",X:["ytp-ce-website-goto","ytp-ce-link"],N:{href:Q1(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",N:P1(b)},{F:"div",I:"ytp-ce-expanding-icon",N:R1(b.iconUrl)}]};c=new g.X(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={F:"div",I:"ytp-ce-merchandise-price-container",
K:[{F:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({F:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={F:"div",X:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":b.ij||"","aria-hidden":"true"},K:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",K:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",K:[{F:"div",
I:"ytp-ce-expanding-overlay-body",K:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{F:"div",I:"ytp-ce-merchandise-title",N:{dir:g.kn(b.title||"")},W:b.title},c,{F:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{F:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:Q1(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",N:P1(b)},{F:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{F:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.X(c)}b.BE&&g.L(c.element,"ytp-ce-placeholder");return c},P1=function(a){if(a.Ru)var b=a.Ru.thumbnails;
return R1(b?b[b.length-1].url:null)},R1=function(a){return a?{style:"background-image: url("+a+")"}:{}},Boa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ha("mouseenter",(0,g.x)(a.Jq,a,b,c));b.ha("mouseleave",(0,g.x)(a.Mr,a,b,c));a.player.O().o||b.ha("click",(0,g.x)(function(l){g.L(l.element,"ytp-ce-element-hover")},a,b));
b.ha("click",(0,g.x)(a.Hy,a,c));b.ha("keypress",(0,g.x)(a.Hy,a,c));b.ha("focus",(0,g.x)(function(l,m){this.Jq(l,m)},a,b,c));
b.ha("blur",(0,g.x)(function(l,m){this.Mr(l,m)},a,b,c));
b.ha("touchstart",(0,g.x)(a.Jq,a,b,c));var f=g.zd("ytp-ce-expanding-overlay-hider",b.element);f&&b.M(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.dn(b.element,"ytp-ce-element-hover");g.dn(b.element,"ytp-ce-force-expand")});
b.ha("keydown",(0,g.x)(function(l,m){this.S=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.L(l.element,"ytp-ce-force-expand"),S1(this,m.id,!0)):(g.dn(l.element,"ytp-ce-force-expand"),g.dn(l.element,"ytp-ce-element-hover"),S1(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ha("blur",g.Oa(function(){"none"!=m.style.display&&a.S&&m.focus()})),l.M(m,"focus",d),l.M(m,"blur",e))},a,b);
c(g.zd("ytp-sb-subscribe",b.element));c(g.zd("ytp-sb-unsubscribe",b.element));b.ha("focus",d);b.ha("blur",e)},Q1=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.oy(c)+b}else return"";return b},S1=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.N(a.o[d].element,"ytp-ce-element-shadow-show",c)},T1=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||N1(a))c&&c();else{b=Coa(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Hp(b[a],d)}},U1=function(a,b,c){T1(a,b.clickUrls,c);
(a=g.YA())&&b.xE&&g.RA(a,b.visualElement)},Coa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Doa(b[e],c));return d},Doa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},V1=function(a){return g.Ia(a)&&a.length?a[0]:a},W1=function(a){return"string"===typeof a?a:""},X1=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Foa=function(a){var b=Eoa;
if(null==a)return null;if(g.Ja(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Goa=function(a){this.externalId=a},Y1=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},Z1=function(a){if(!a)return null;
var b=g.yc(W1(a.value));b=g.wc(b);if(!b)return null;var c=X1(a.target,Hoa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Y1(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},$1=function(a){return a.value?a.value:null},a2=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Eoa=function(a){if(!a)return null;
var b=X1(a.type,Ioa),c=X1(a.trigger,Joa),d=V1(a.url);d=Z1(d?d:null);a=V1(a.subscribeData);var e=a?a:null;e?(a=W1(e.external_user_id),e=W1(e.subscription_token),a=a&&e?new Goa(a):null):a=null;return b?new a2(b,c,d,a):null},b2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},c2=function(a){return(a=Koa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Koa=function(a,b){return g.Va(a.o,b,void 0)},d2=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Loa=function(a,b){this.merchant=a;
this.price=b},Moa=function(a){this.o=a},Noa=function(a,b,c){b&&(c?e2(a,(0,g.H)(b,g.Oa(function(d,e){return g.Pm(e,d)},c))):e2(a,b))},e2=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Hp(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Ooa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.Ya=c;this.videoData=d;this.logger=e;this.ca=f;this.u=k},f2=function(a,b){this.o=a;
this.w=b},Qoa=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Poa(b,k))},a);
var d={F:"ul",N:{role:"radiogroup"},K:c},e={};b.Ih&&(e["aria-label"]=g.zN("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{F:"div",I:"iv-card-content",K:[g2("h2",e,b.title),{F:"form",K:[{F:"fieldset",K:[d]}]}]}];b.Ih&&(f.push("iv-card-unavailable"),d.push({F:"div",X:["iv-card-sign-in"],K:[{F:"h2",W:"Want to vote?"},{F:"a",X:["iv-card-sign-in-button","iv-button"],N:{href:$1(b.Ih)},K:[{F:"span",X:["iv-button-content"],W:"Sign in"}]}]}));f=new g.X({F:"div",
X:f,K:d});d=f.element;h2(b,d);xoa(a.o.o,d,g.Oa(a.A,b),a);(0,g.y)(g.yd("iv-card-poll-choice-input",d),function(k){this.o.o.ha(k,"focus",g.Oa(this.u,!0));this.o.o.ha(k,"blur",g.Oa(this.u,!1))},a);
b.Ih&&(d=g.zd("iv-card-sign-in-button",d),a.w(d,b.Ih,b.id,b.Gb,b.qc.click,5));return f},l2=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.QN?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.AE&&b.qu?{F:"span",X:d,N:e,W:b.qu}:"";c={F:"div",X:["iv-card",c],K:[{F:"a",I:"iv-click-target",N:{href:$1(b.url)},K:[i2(b.Lh,d?{F:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{F:"div",I:"iv-card-content",K:[{F:"h2",I:"iv-card-primary-link",W:b.title},j2(a,b)]}]}]};c=new g.X(c);k2(a,g.yd("iv-click-target",c.element),b,b.url);return c},m2=function(a){return a.customMessage?
g2("div","iv-card-message",a.customMessage):""},i2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{F:"div",I:"iv-card-image",N:{style:c},K:d}},j2=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(g2("li","",d))},a);
return{F:"ul",I:"iv-card-meta-info",K:c}},Poa=function(a,b){return{F:"li",
I:d2(a,b.index),K:[{F:"label",K:[{F:"input",I:"iv-card-poll-choice-input",N:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{F:"span",I:"iv-card-poll-choice-text",K:[{F:"span",I:"iv-card-poll-choice-percent"},g2("span",void 0,b.desc)]}]},{F:"div",I:"iv-card-poll-result",K:[{F:"div",I:"iv-card-poll-result-bar"}]}]}},g2=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ia(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.kn(c);return{F:a,N:b,W:c}},n2=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Dl&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Dl+");");c.dir=g.kn(a.customMessage);var d=[{F:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",I:"iv-card-link-icon"}));return{F:"div",X:b,N:c,K:d}},h2=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.zd(d2(a,e.index),b);e=e.count/c;null==a.ge&&(e=0);g.N(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.ge==d);f.getElementsByTagName("input")[0].checked=a.ge==d;var k=Math.floor(100*e).toFixed(0),l=g.zd("iv-card-poll-choice-percent",f);g.Vd(l,g.zN("$PERCENT%",{PERCENT:k}));f=g.zd("iv-card-poll-result-bar",f);g.kh(f,"transform","scaleX("+e.toFixed(2)+")")}g.N(b,"iv-card-poll-voted",null!=a.ge);g.N(b,"iv-card-poll-expanded",
null!=a.ge&&1<a.choices.length)},k2=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Gb,c.qc.click,5)},a)},o2=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Roa=function(a,b){return b?b:o2(a)?"current":"new"},p2=function(a,b){g.A.call(this);
this.o=a;this.context=b;this.ct=!1},Soa=function(a,b,c,d,e){var f=$1(b);
if(f){var k=Roa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.ca.pauseVideo();var m=this.context.videoData.Zb||!1,n=g.Wo(f||"");m&&n&&(n.v||n.list)?g.sU(this.context.ca.app,n.v,c,n.list,!1,void 0):g.FN(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);e2(a.context.logger,d,l,e);o2(f)||(a=g.YA(),d=c.itct,a&&d&&g.RA(a,g.CA(d)))}},q2=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},r2=function(a,b,c){return{gw:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
xA:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
co:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},u2=function(a,b,c){p2.call(this,b,c);
var d=this;this.w=a;this.Z=this.ya=this.C=this.xa=!1;this.aa=null;this.da=new g.J(g.Ea,c.Ya.Oa?4E3:3E3);g.B(this,this.da);this.la=new g.J(g.Ea);g.B(this,this.la);this.H=new f2(c,(0,g.x)(this.Ti,this),(0,g.x)(this.Lm,this));this.U=new g.X({F:"div",I:"iv-drawer",N:{id:"iv-drawer"},K:[{F:"div",I:"iv-drawer-header",N:{"aria-role":"heading"},K:[{F:"span",I:"iv-drawer-header-text"},{F:"button",X:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",I:"iv-drawer-content"}]});
g.B(this,this.U);this.D=this.U.element;this.ra=new g.SM(this.U,330);g.B(this,this.ra);this.wa=g.zd("iv-drawer-header-text",this.D);this.B=g.zd("iv-drawer-content",this.D);this.A=[];this.oa=this.P=this.G=this.ga=this.u=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.ya&&s2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ya=d.C)&&t2(d)});
this.L=this.J=this.ba=null;this.S=0},Toa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){s2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){t2(a)});
var c=b.data.headerText;g.Vd(a.wa,c);a.P&&a.P.setAttribute("title",c);a.ba=g.CA(b.data.trackingParams);a.L=g.CA(b.data.closeTrackingParams);a.J=g.CA(b.data.iconTrackingParams)},Uoa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.S;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.S,type:"simple",teaserText:g.qA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:v2(a,c,b,d),sponsored:!1,qc:r2(d,e,d.command),Hd:d.trackingParams?g.CA(d.trackingParams):null,Bd:e.trackingParams?
g.CA(e.trackingParams):null,Tc:f&&f.trackingParams?g.CA(f.trackingParams):null,imageUrl:d.image.thumbnails[0].url,displayDomain:d.displayDomain?g.qA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Dl:null,title:d.title?g.qA(d.title):"",customMessage:d.callToAction?g.qA(d.callToAction):"",url:d.command.urlEndpoint.url?Z1({pause_on_navigation:!a.context.videoData.sa,target:"new",value:d.command.urlEndpoint.url}):null};w2(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.S,type:"collaborator",teaserText:g.qA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:v2(a,c,b,d),sponsored:!1,qc:r2(d,e,d.endpoint),Hd:d.trackingParams?g.CA(d.trackingParams):null,Bd:e.trackingParams?g.CA(e.trackingParams):null,Tc:f&&f.trackingParams?
g.CA(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.qA(d.customText):null,wz:d.channelAvatar.thumbnails[0].url,title:d.channelName?g.qA(d.channelName):"",metaInfo:[d.subscriberCountText?g.qA(d.subscriberCountText):""],url:Z1({pause_on_navigation:!a.context.videoData.sa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};w2(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.S,type:"playlist",teaserText:g.qA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:v2(a,c,b,d),sponsored:!1,qc:r2(d,e,d.action),Hd:d.trackingParams?g.CA(d.trackingParams):null,Bd:e.trackingParams?g.CA(e.trackingParams):null,Tc:f&&f.trackingParams?g.CA(f.trackingParams):
null,Lh:d.playlistThumbnail.thumbnails[0].url,customMessage:d.customMessage?g.qA(d.customMessage):null,playlistVideoCount:g.qA(d.playlistVideoCount),title:d.playlistTitle?g.qA(d.playlistTitle):"",metaInfo:[d.channelName?g.qA(d.channelName):"",d.videoCountText?g.qA(d.videoCountText):""],url:Z1({pause_on_navigation:!a.context.videoData.sa,target:"new",value:q2(d.action)})};w2(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.S,type:"video",teaserText:g.qA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:v2(a,c,b,d),sponsored:!1,qc:r2(d,e,d.action),Hd:d.trackingParams?g.CA(d.trackingParams):null,Bd:e.trackingParams?g.CA(e.trackingParams):null,Tc:f&&f.trackingParams?g.CA(f.trackingParams):null,Lh:d.videoThumbnail.thumbnails[0].url,
videoDuration:d.lengthString?g.qA(d.lengthString):null,customMessage:d.customMessage?g.qA(d.customMessage):null,title:d.videoTitle?g.qA(d.videoTitle):"",metaInfo:[d.channelName?g.qA(d.channelName):"",d.viewCountText?g.qA(d.viewCountText):""],isLiveNow:!!d.badge,url:Z1({pause_on_navigation:!a.context.videoData.sa,target:"new",value:q2(d.action)})};w2(a,c)}a.S++},v2=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},y2=function(a,b){var c=Voa(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.Qd(c.Zo),g.bb(a.A,c),a.Fl(),x2(a))},s2=function(a,b,c){if(!a.C){a.ra.show();
a.ga=new g.J(function(){g.L(a.context.ca.getRootNode(),"ytp-iv-drawer-open")},0);
a.ga.start();a.aa=g.Xq(a.B,"mousewheel",(0,g.x)(a.HF,a));a.C=!0;var d=g.YA();d&&a.ba&&a.L&&w1(d,[a.ba,a.L]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.Iw||(f.Iw=!0,Noa(a.context.logger,f.card.qc.gw,e));d&&w1(d,[f.card.Hd])});
v1(a.w);c&&(a.G=new g.J(function(){a.fa=a.P;a.oa.focus()},330),a.G.start())}},t2=function(a){a.C&&(a.ra.hide(),g.Yq(a.aa),a.aa=null,g.dn(a.context.ca.getRootNode(),"ytp-iv-drawer-open"),a.C=!1,v1(a.w),a.G&&a.G.stop(),a.G=new g.J(function(){a.fa&&(a.fa.focus(),a.fa=null)},330),a.G.start())},Woa=function(a){var b=g.zd("iv-drawer-close-button",a.D);
a.context.o.ha(b,"click",a.EC,a);a.context.o.ha(a.B,"touchend",function(){a.da.start()});
a.context.o.ha(a.B,"scroll",a.SC,a);a.context.u.subscribe("onHideControls",function(){a.Z=!0});
a.context.u.subscribe("onShowControls",function(){a.Z=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Z=g.bn(a.w.getRootNode(),"ytp-autohide")});
a.V.push(g.wo("iv-button-shown",a.ME,a));a.V.push(g.wo("iv-button-hidden",a.LE,a));a.V.push(g.wo("iv-teaser-shown",a.PE,a));a.V.push(g.wo("iv-teaser-hidden",a.OE,a));a.V.push(g.wo("iv-teaser-clicked",a.NE,a))},w2=function(a,b){a.xa||(g.cn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.oL(a.w,a.D,5),Woa(a),a.P=g.zd("ytp-cards-button",a.w.getRootNode()),a.oa=g.zd("iv-drawer-close-button",a.D),a.xa=!0);y2(a,b.id);var c=Xoa(a,b);if(c){var d={card:b,Zo:c.element,Iw:!1},e=Yoa(a,d);g.ib(a.A,e,0,d);c.o(a.B,e);a.Fl();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Oa(a.gN,d)):(c=1E3*a.context.ca.getCurrentTime(),5E3>c&&c>b.startMs&&a.dA(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Oa(a.dA,d)),x2(a))}},Xoa=function(a,b){switch(b.type){case "simple":var c=
a.H;
var d=b.displayDomain?{F:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=n2(b);d={F:"div",X:["iv-card"],K:[{F:"a",I:"iv-click-target",N:{href:$1(b.url)},K:[i2(b.imageUrl,d),{F:"div",I:"iv-card-content",K:[g2("h2",void 0,b.title),e]}]}]};d=new g.X(d);k2(c,g.yd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={F:"div",X:["iv-card","iv-card-channel"],K:[{F:"a",X:["iv-click-target"],N:{href:$1(b.url),"data-ytid":b.channelId},K:[i2(b.wz),{F:"div",I:"iv-card-content",
K:[m2(b),{F:"h2",I:"iv-card-primary-link",W:b.title},j2(c,b)]}]}]},d=new g.X(d),k2(c,g.yd("iv-click-target",d.element),b,b.url),d;case "episode":return l2(a.H,b,"iv-card-episode");case "movie":return l2(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={F:"div",X:["iv-card","iv-card-playlist"],K:[{F:"a",I:"iv-click-target",N:{href:$1(b.url)},K:[i2(b.Lh,{F:"div",I:"iv-card-image-overlay",K:[{F:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{F:"div",I:"iv-card-content",K:[m2(b),
g2("h2","iv-card-primary-link",b.title),j2(c,b)]}]}]},d=new g.X(d),k2(c,g.yd("iv-click-target",d.element),b,b.url),d;case "poll":return Qoa(a.H,b);case "productListing":c=a.H;var f=!g.Za(b.offers);d=["iv-card"];e="";var k=n2(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({F:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({F:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={F:"div",K:k});d={F:"div",X:d,N:{tabindex:"0"},K:[{F:"a",X:["iv-card-image",
"iv-click-target"],N:{style:"background-image: url("+b.imageUrl+");",href:$1(b.url),"aria-hidden":"true",tabindex:"-1"}},{F:"div",I:"iv-card-content",K:[b.sponsored?{F:"div",I:"iv-card-sponsored",K:["Sponsored",{F:"div",I:"iv-ad-info-container",K:[{F:"div",I:"iv-ad-info",W:"{{adInfo}}"},{F:"div",I:"iv-ad-info-icon-container",K:[{F:"div",I:"iv-ad-info-icon"},{F:"div",I:"iv-ad-info-callout"}]}]}]}:"",{F:"a",I:"iv-click-target",N:{href:$1(b.url)},K:[g2("h2",e,b.title),k]}]}]};d=new g.X(d);e=g.Ld("span");
g.Vd(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.jb(e,"adInfo");k2(c,g.yd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{F:"span",X:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={F:"div",X:["iv-card","iv-card-video"],K:[{F:"a",I:"iv-click-target",N:{href:$1(b.url)},K:[i2(b.Lh,b.videoDuration?{F:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{F:"div",I:"iv-card-content",
K:[m2(b),g2("h2","iv-card-primary-link",b.title),j2(c,b),d]}]}]},d=new g.X(d),k2(c,g.yd("iv-click-target",d.element),b,b.url),d}return null},Yoa=function(a,b){if(0==a.A.length)return 0;
var c=g.Wa(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Zoa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.mi)(a.A,function(b){return"productListing"==b.card.type})},x2=function(a){g.N(a.w.getRootNode(),"ytp-cards-shopping-active",Zoa(a))},z2=function(a,b){if(a.U.Ha()){var c=new D1([0,
a.B.scrollTop],[0,b.Zo.offsetTop],600,voa);a.context.w.ha(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ha(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.nK(a.U,!0),a.B.scrollTop=b.Zo.offsetTop,g.nK(a.U,!1)},A2=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},Voa=function(a,b){return g.Va(a.A,function(c){return c.card.id==b})},B2=function(a,b,c){p2.call(this,a,b);
this.annotation=c;this.isActive=!1},$oa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},C2=function(a,b,c){B2.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.D=this.C=null},D2=function(a,b,c){B2.call(this,a,b,c);
this.J=this.C=this.S=!1;this.G=5E3;this.B=null;this.H=g.Kd("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.D=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.Fh(this.A,!1);g.Fh(this.w,!0)},700,this);
g.B(this,this.D)},apa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=c2(a.annotation),f=b.image_url;if(f){var k=g.Kd("DIV",["iv-promo-img","iv-click-target"]);f=g.Kd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Kd("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Kd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Ti(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Kd("A","iv-promo-txt"),g.Qc(f,$1(e)),a.u=f):a.u=g.Kd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Kd("P",null,g.Kd("STRONG",null,b.text_line_1));var m=g.Kd("P",null,g.Kd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.S(a.context.Ya.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Kd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Kd("BUTTON",["iv-button","iv-promo-button"],g.Kd("SPAN","iv-button-content",f));var q=g.Kd("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Ti(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.L(a.u,"iv-click-target");e&&a.Ti(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Kd("P",null,g.Kd("SPAN",null,b.text_line_1)),
m=g.Kd("P",null,g.Kd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Kd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.L(a.u,"iv-click-target"),e&&a.Ti(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Kd("DIV","iv-promo-actions");a.w=g.Kd("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ha(a.w,"click",g.Oa(a.Qp,5E3),a);c.appendChild(a.w);g.Fh(a.w,!1);
a.context.o.ha(a.o,"mouseover",a.PD,a);a.context.o.ha(a.o,"mouseout",a.OD,a);a.context.o.ha(a.o,"touchend",g.Oa(a.Qp,5E3),a);a.A=g.Kd("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ha(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.ID:a.HD,a);c.appendChild(a.A);g.cn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},E2=function(a){a.C||a.J||a.B||(g.L(a.o,"iv-promo-collapsed"),a.C=!0,a.D.start())},F2=function(a){a.D.stop();
a.C&&(g.en(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Fh(a.w,!1),g.Fh(a.A,!0))},H2=function(a,b){a.B||(a.B=g.qf(function(){G2(this);
E2(this)},b,a))},G2=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},I2=function(a){g.EQ.call(this,a);
this.J=!1;this.H=0;this.D={};this.U=new Moa(a);this.B=new g.R(this);g.B(this,this.B);this.C=this.w=null;this.B.M(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.M(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.M(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.M(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.M(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.QK,this);this.subscribe("resize",this.Dn,this);this.player.O().D.subscribe("vast_info_card_add",this.jz,this);this.P=new g.R(this);g.B(this,this.P);this.L=g.Kd("DIV","video-custom-annotations");this.u=new g.X({F:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.B(this,this.u);g.oL(this.player,this.u.element,4);this.u.hide();this.A=new g.X({F:"div",X:["ytp-iv-video-content"]});g.B(this,this.A);g.Nd(this.A.element,g.Kd("DIV","video-annotations",
this.L));this.G=this.o=null;this.S=[];bpa(this)&&this.load();var b=g.Ld("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ce(this,function(){g.Qd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},J2=function(){var a=g.Kd("DIV",["annotation",
"annotation-type-custom"]);g.Fh(a,!1);return a},K2=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},bpa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.dB||null!==b.D.get(a.videoId)},L2=function(a,b,c){a.J=!0;
a.C=g.op(b,c)},M2=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(M2(a,e))}return c},N2=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},cpa=function(a){var b=a.player.getVideoData();
if(b.Gd){var c=a.player.O().D.get(b.videoId);if(c){var d={format:"XML",Dd:{},method:"POST",withCredentials:!0};d.Zc=(0,g.x)(function(e,f,k){N2(this,e,f)||(e=g.ip(k)&&k.responseXML?k.responseXML:null)&&O2(this,e)},a,a.H,b.videoId);
g.Lo()&&(d.Zc=P2(a,d.Zc));d.ub={ic_only:"1"};Q2(d,c);a.J=!0;g.op(b.Gd,d)}}},Q2=function(a,b){a.method="POST";
a.ub=a.ub||{};b.Jl&&(a.ub.ic_coll=b.Jl);b.Kl&&(a.ub.ic_xml=b.Kl);b.Wk&&(a.ub.ic_track=b.Wk)},S2=function(a){var b=new g.X({F:"div"});
g.Fh(b.element,!1);var c=new u2(a.player,b.element,R2(a));g.B(c,b);b.o(a.u.element);c.Kk();return c},R2=function(a){if(!a.G){var b=new I1(a);
g.B(a,b);var c=new g.W_(a);g.B(a,c);a.G=new Ooa(b,c,a.player.O(),a.player.getVideoData(),a.U,a.player,a.Vb)}return a.G},O2=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.YA();if(e){var f=g.XA();f&&g.PA(e,f,[g.CA(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=M2(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=X1(k.type,dpa),t=X1(k.style,epa),u=W1(k.data),z=0!=u.length?JSON.parse(u):{},C=Foa(k.action);f=n&&q?new b2(n,q,t,C,z):null}else f=null}catch(M){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var D=J2(),G=null;switch(m.type){case "branding":if(k.player.O().La)break;k.u.element.appendChild(D);G=new C2(D,R2(k),m);break;case "promotion":g.oL(k.player,D,4),G=new D2(D,R2(k),m)}G&&G.Kk();if(k=G)g.B(a,k),a.D[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=S2(a),g.B(a,a.o));if("card"==f.type){if(c=a.o,G=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={gw:k.impression,click:k.click,close:k.close,xA:k.teaser_impression,co:k.teaser_click},m=f.data.tracking_params||
{},D=null,G){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,qc:k,Hd:m.card?g.CA(m.card):null,Bd:m.teaser?g.CA(m.teaser):null,Tc:m.icon?g.CA(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,wz:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:Z1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};w2(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,qc:k,Hd:m.card?g.CA(m.card):null,Bd:m.teaser?g.CA(m.teaser):null,Tc:m.icon?g.CA(m.icon):
null,Lh:f.data.image_url,qu:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,AE:!!f.data.is_paygated,QN:!!f.data.user_has_entitlement,url:Z1({target:f.data.target||"new",value:f.data.url})};w2(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,qc:k,Hd:m.card?g.CA(m.card):null,Bd:m.teaser?g.CA(m.teaser):null,Tc:m.icon?g.CA(m.icon):null,Lh:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:Z1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};w2(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,qc:k,Hd:m.card?g.CA(m.card):null,Bd:m.teaser?g.CA(m.teaser):null,Tc:m.icon?g.CA(m.icon):null,title:f.data.title,choices:f.data.choices,ge:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Ih:f.data.signin_url?Z1({target:"current",value:f.data.signin_url}):null,bO:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};w2(c,f);break;case "productListing":f.data.signin_url&&(D=Z1({target:"current",
value:f.data.signin_url}));G=[];for(var K=f.data.offers||[],F=0;F<K.length;F++)G.push(new Loa(g.Yc(K[F].merchant),g.Yc(K[F].price)));f={ZR:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,qc:k,Hd:m.card?g.CA(m.card):null,Bd:m.teaser?g.CA(m.teaser):null,Tc:m.icon?g.CA(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Dl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:Z1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Ih:D,lS:f.data.signin_title?f.data.signin_title:null,kS:f.data.signin_message?f.data.signin_message:null,offers:G};w2(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,qc:k,Hd:m.card?g.CA(m.card):null,Bd:m.teaser?g.CA(m.teaser):null,Tc:m.icon?g.CA(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Dl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:Z1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};w2(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,qc:k,Hd:m.card?g.CA(m.card):null,Bd:m.teaser?g.CA(m.teaser):
null,Tc:m.icon?g.CA(m.icon):null,Lh:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:Z1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},w2(c,f)}}else Toa(a.o,f);c=!0}}}c&&(v1(a.player),a.Dn())},fpa=function(a,b){var c=!1;
a.o||(a.o=S2(a),g.B(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Uoa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.qA(b.headerText):"",g.Vd(c.wa,d),c.P&&c.P.setAttribute("title",d),c.ba=b.trackingParams?g.CA(b.trackingParams):null,c.L=b.closeButton.infoCardIconRenderer.trackingParams?g.CA(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.CA(b.icon.infoCardIconRenderer.trackingParams):null,v1(a.player),a.Dn())},
gpa=function(a,b,c,d,e){if(!a.player.O().La){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new a2("openUrl","click",new Y1("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;b.subscribed?(e=g.qA(b.subscriberCountWithUnsubscribeText),k=g.qA(b.subscriberCountText)):(e=g.qA(b.subscriberCountText),k=g.qA(b.subscriberCountWithSubscribeText));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.qA(b.unsubscribedButtonText),
subscribeCount:e,unsubscribeText:g.qA(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new b2(c,"branding","branding",f,d);d=J2();a.u.element.appendChild(d);f=new C2(d,R2(a),f);f.Kk();g.B(f,f);a.D[c]=f}},P2=function(a,b){return(0,g.x)(function(){if(!this.ia()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Oa.apply(window,c);this.S.push(g.Jo(b))}},a)},y1={},z1=null;g.Qa(D1,g.fn);g.h=D1.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;A1(this);this.startTime=a=(0,g.E)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.B();this.Wd("play");-1==this.o&&this.Wd("resume");this.o=1;var b=g.Na(this);b in y1||(y1[b]=this);B1();C1(this,a);return!0};
g.h.stop=function(a){A1(this);this.o=0;a&&(this.progress=1);E1(this,this.progress);this.Wd("stop");this.A()};
g.h.pause=function(){1==this.o&&(A1(this),this.o=-1,this.Wd("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.Wd("destroy");D1.xb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Gr=function(){this.Wd("animate")};
g.h.Wd=function(a){this.dispatchEvent(new F1(a,this))};
g.Qa(F1,g.fe);g.Qa(G1,D1);G1.prototype.C=g.Ea;G1.prototype.Gr=function(){this.C();G1.xb.Gr.call(this)};
G1.prototype.A=function(){this.C();G1.xb.A.call(this)};
G1.prototype.B=function(){this.C();G1.xb.B.call(this)};
g.Qa(H1,G1);H1.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(I1,g.A);I1.prototype.ha=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Xq(a,b,c);this.o.push(a);return a};
I1.prototype.wq=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.gr(a,b,c);this.o.push(a);return a};
I1.prototype.Ua=function(a){g.Yq(a);g.bb(this.o,a)};
I1.prototype.Y=function(){g.Yq(this.o);this.o.length=0;g.A.prototype.Y.call(this)};g.r(L1,g.EQ);g.h=L1.prototype;g.h.load=function(){g.EQ.prototype.load.call(this);if(!N1(this)){var a=g.EC(this.player.getVideoData());if(a)a=K1(a,M1(this)),O1(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",Zc:(0,g.x)(this.CJ,this,a),Dd:{v:a},withCredentials:!0};this.J&&(a.Dd.ptype="embedded");var c=this.player.getVideoData().Wl;c&&(a.ub={ad_tracking:c});if(b=g.DC(b))if(b=g.yc(b),b=g.wc(b))this.A=g.op(b,a)}}};
g.h.unload=function(){O1(this,null);this.A&&(this.A.abort(),this.A=null);g.EQ.prototype.unload.call(this)};
g.h.xc=function(a,b){if(!N1(this))return null;if("loadCustomEndscreenRenderer"==a){var c=K1(b,"new");O1(this,c);return!0}return null};
g.h.getOptions=function(){return N1(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.CJ=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=K1(c,M1(this)))}O1(this,c)};
g.h.Uw=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<T2.length;f++){var k=Math.abs(b.width-T2[f]);if(-1==e||d>=k)e=f,d=k}d=U2[e];this.w&&g.kh(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Dh(e.element,Math.round(k.width*a.width),f);g.th(e.element,m,n);g.en(e.element,hpa);m=k.left+k.width/2;k=k.top+l/2;g.L(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.en(e.element,U2);g.L(e.element,d);(e=g.xd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.kh(e,"height",f+"px")}}}}};
g.h.kF=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())T1(this,this.u.impressionUrls),(a=g.YA())&&this.u.visualElement&&g.QA(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.D[a];g.L(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.L(b,"ytp-ce-shown");T1(this,c.impressionUrls);(b=g.YA())&&g.QA(b,c.visualElement);this.player.O().wb&&this.player.ma("endscreenelementshown",a)}};
g.h.lF=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.dn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.dn(b,"ytp-ce-shown");this.player.O().wb&&this.player.ma("endscreenelementhidden",a)}};
g.h.sM=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.en(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Hy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.bn(c,"ytp-ce-element");){g.bn(c,"subscribe-label")&&U1(this,a);if(g.bn(c,"ytp-ce-channel-subscribe"))return;c=g.Td(c)}if(!c||g.bn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Mr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.xN?(U1(this,a),this.cA(),this.player.pauseVideo(),c=g.yc(Q1(this,a.targetUrl)),c=g.wc(c),g.FN(c,void 0,a.Gb)):(c=this.player.getVideoData().Zb,
c=(0,g.x)(this.oN,this,c,Q1(this,a.targetUrl),a.Gb),c=(0,g.x)(this.cA,this,c),U1(this,a,c))}}};
g.h.oN=function(a,b,c){var d=g.Wo(b);a&&d&&(d.v||d.list)?g.sU(this.player.app,d.v,c,d.list,!1,void 0):g.EN(b,c)};
g.h.Jq=function(a,b){g.bn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.L(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.J(function(){g.L(a.element,"ytp-ce-element-hover")},200)).start():g.L(a.element,"ytp-ce-element-hover"),T1(this,b.nE),S1(this,b.id,!0))};
g.h.Mr=function(a,b){g.dn(a.element,"ytp-ce-element-hover");g.dn(a.element,"ytp-ce-force-expand");S1(this,b.id,!1)};
g.h.cA=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var T2=[346,426,470,506,570,640,853,1280,1920],U2="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),hpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Hoa={hP:"current",BQ:"new"};var Ioa={CLOSE:"close",EQ:"openUrl",XB:"subscribe"},Joa={aP:"click",CLOSE:"close",SP:"hidden",bR:"rollOut",cR:"rollOver",fR:"shown"};var epa={DO:"anchored",tB:"branding",CHANNEL:"channel",gP:"cta",UP:"highlightText",kQ:"label",PLAYLIST:"playlist",OQ:"popup",jR:"speech",XB:"subscribe",tR:"title",VIDEO:"video",GR:"website"},dpa={tB:"branding",RO:"card",nP:"drawer",TP:"highlight",rQ:"marker",TQ:"promotion",TEXT:"text",IR:"widget"};f2.prototype.u=function(a,b){var c=g.ae(b.target,"label");c&&g.N(c,"iv-card-poll-choice-focused",a)};
f2.prototype.A=function(a,b){var c=g.ae(b.target,null,"iv-card-poll",void 0);if(c)if(a.Ih)g.zd("iv-card-sign-in-button",c).click();else{var d=parseInt(toa(b.target),10);if(null==a.ge)a.choices[d].count++,a.ge=d;else if(a.ge!=d){var e=a.choices[a.ge];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.ge=d}else e=a.choices[a.ge],e.count=Math.max(e.count-1,0),a.ge=null;h2(a,c);g.sp(this.o.videoData.Gd,{Dd:{action_poll_vote:1},ub:{poll_id:a.id,index:d,session_token:a.bO}});e2(this.o.logger,a.qc.click,
void 0,5);(c=g.YA())&&a.Hd&&g.RA(c,a.Hd)}};g.r(p2,g.A);g.h=p2.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.hF(a,b,{id:c});g.B(this,a);a.namespace="annotations_module";d&&u1(a).subscribe("onEnter",d,this);e&&u1(a).subscribe("onExit",e,this);g.kL(this.context.ca,[a])};
g.h.Kk=function(){this.context.u.subscribe("resize",this.Fl,this)};
g.h.Ti=function(a,b,c,d,e,f){this.context.o.ha(a,"click",g.Oa(this.Lm,b,c,d,e||[],f||0),this);this.context.o.ha(a,"touchstart",g.Oa(function(){this.ct=!1}),this);
this.context.o.ha(a,"touchmove",g.Oa(function(){this.ct=!0}),this)};
g.h.Lm=function(a,b,c,d,e,f){if(this.ct)return!1;f&&(f.stopPropagation(),f.preventDefault());Soa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Qd(this.o)};
g.h.Fl=function(){};g.r(u2,p2);g.h=u2.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.w.getRootNode())?(a=g.Eh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Fl=function(){var a=this.isAvailable();g.Fh(this.o,a);g.N(this.context.ca.getRootNode(),"ytp-iv-drawer-enabled",a);v1(this.w)};
g.h.destroy=function(){var a=g.cL(g.RK(this.w));a&&a.Iq(!1,void 0);this.w.getRootNode().removeChild(this.D);g.xo(this.V);g.Yq(this.aa);this.ga&&this.ga.dispose();this.G&&this.G.dispose();p2.prototype.destroy.call(this)};
g.h.HF=function(a){this.da.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.dA=function(a){if(!g.bn(this.w.getRootNode(),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.YA(),c=this.u?this.u.card.Tc:this.J;b&&c&&x1(b,[c]);this.u=a;x2(this)}if(b="none"!=this.o.style.display)2==this.context.ca.getPresentingPlayerType()?b=1==this.context.ca.getAdState():(b=this.context.ca.getPlayerState(),c=0==b&&0===this.context.ca.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.cL(g.RK(this.w)))&&c.Iq(!0,
b));this.la.isActive()||((!this.C||!this.da.isActive()&&this.Z)&&z2(this,a),this.la.start(910+a.card.teaserDurationMs))}};
g.h.gN=function(a){this.C||(this.u=a,x2(this),z2(this,a),s2(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.EC=function(){if(this.C){e2(this.context.logger,A2(this).qc.close);var a=g.YA();a&&this.L&&g.RA(a,this.L);t2(this)}};
g.h.SC=function(){g.N(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.ME=function(){var a=g.YA(),b=A2(this);b=b?b.Tc:this.J;a&&b&&w1(a,[b])};
g.h.LE=function(){var a=g.YA(),b=A2(this);b=b?b.Tc:this.J;a&&b&&x1(a,[b])};
g.h.PE=function(){var a=A2(this);e2(this.context.logger,a.qc.xA);var b=g.YA();b&&a&&w1(b,[a.Bd,a.Tc])};
g.h.OE=function(){var a=g.YA(),b=A2(this);a&&b&&x1(a,[b.Bd])};
g.h.NE=function(a){var b=A2(this),c=g.YA();this.u?a?(a=this.context.logger,e2(a,b.qc.co),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Bd&&g.RA(c,b.Bd)):(a=this.context.logger,e2(a,b.qc.co),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Tc&&g.RA(c,b.Tc)):(a=this.context.logger,e2(a,b.qc.co),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.RA(c,this.J))};g.r(B2,p2);B2.prototype.Kk=function(){p2.prototype.Kk.call(this);$oa(this)};
B2.prototype.show=function(){p2.prototype.show.call(this);var a=g.YA(),b=this.annotation.data;a&&b&&(b=b.session_data)&&w1(a,[g.CA(b.itct)])};
B2.prototype.hide=function(){p2.prototype.hide.call(this);var a=g.YA(),b=this.annotation.data;a&&b&&(b=b.session_data)&&x1(a,[g.CA(b.itct)])};g.r(C2,B2);g.h=C2.prototype;g.h.pN=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Eh(a);this.u||(g.Ch(a,e.width),g.Ch(b,e.width));g.kh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.kh(c,"right","1px");this.B=!0;g.Fh(a,!0);this.C=new g.J(function(){g.L(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.lE=function(a,b){g.dn(this.o,"iv-branding-active");this.D=new g.J((0,g.x)(function(){g.Fh(a,!1);this.u||g.Ch(b,0)},this),250);
this.D.start();this.B=!1};
g.h.show=function(){if(!this.isActive){B2.prototype.show.call(this);if(!this.G){g.L(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Kd("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Fh(this.w,!1);var b=g.Kd("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=c2(this.annotation))&&this.Ti(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Kd("DIV","iv-branding-context-name");
g.Vd(c,a.channel_name);var d=g.Kd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.jR(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.ca),this.u.o(d);b=g.Kd("DIV","iv-branding-context-subscribe-caret");c=g.Kd("DIV","branding-context-container-inner",b,c,d);g.Fh(c,!1);d=g.Kd("DIV","branding-context-container-outer",c);g.kh(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.J(g.Oa(this.lE,c,d),500,this);g.B(this,this.A);this.context.o.ha(this.o,"mouseover",(0,g.x)(this.pN,this,c,d,b,a.image_height));this.context.o.ha(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Fh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.xh(a);c=g.Eh(a);b=(new g.hh(b.x,b.y,c.width,c.height)).width;g.th(a,b);e=new H1(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,uoa);g.B(this,e);this.context.w.ha(e,
"begin",g.Oa(g.Fh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(B2.prototype.hide.call(this),g.Fh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);B2.prototype.destroy.call(this)};g.r(D2,B2);g.h=D2.prototype;g.h.show=function(){this.isActive||(B2.prototype.show.call(this),this.S||(apa(this),this.S=!0),g.Fh(this.o,!0),g.qf(function(){g.dn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,G2(this),F2(this),H2(this,this.G))};
g.h.hide=function(){this.isActive&&(g.L(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.Lm=function(a,b,c,d,e,f){return this.C?!1:B2.prototype.Lm.call(this,a,b,c,d,e,f)};
g.h.Qp=function(a,b){b.stopPropagation();F2(this);H2(this,a);this.u.focus()};
g.h.PD=function(a){this.J=!0;this.Qp(500,a)};
g.h.OD=function(){this.J=!1;E2(this)};
g.h.HD=function(a){a.stopPropagation();this.hide()};
g.h.ID=function(a){a.stopPropagation();G2(this);this.C=!0;g.L(this.o,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();B2.prototype.destroy.call(this)};g.r(I2,g.EQ);g.h=I2.prototype;g.h.xc=function(a,b){if(!K2(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.V_(b);c&&O2(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(y2(this.o,b),v1(this.player)),!0}return null};
g.h.getOptions=function(){return K2(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Dn=function(){if(this.A){var a=g.XK(this.player).getVideoContentRect(!0);g.Dh(this.A.element,a.width,a.height);g.th(this.A.element,a.left,a.top)}if(this.o){var b=g.fL(this.player);a=this.o;b=b.width;g.N(a.D,"iv-drawer-small",426>=b);g.N(a.D,"iv-drawer-big",1280<=b)}};
g.h.QK=function(a){this.ac(a.state);g.V(a.state,2)&&(this.ek()&&this.Sw()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Iq(!1))};
g.h.load=function(){g.EQ.prototype.load.call(this);this.ac(g.WK(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.EJ,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.Lo()&&(c=P2(this,c));c={format:"XML",Zc:c,onError:d,Dd:{}};a.isPharma&&(c.Dd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().D.get(b))&&Q2(c,b);b=b&&(b.Kl||b.Jl);if(!a.yl||b)a.Gd?L2(this,a.Gd,c):(this.w=(0,g.x)(this.iF,this,c),this.player.addEventListener("videodatachange",this.w));g.oL(this.player,this.A.element,4);this.Dn();(b=a.Ia&&a.Ia.cards&&a.Ia.cards.cardCollectionRenderer||null)&&fpa(this,b);(b=soa(a))&&b.featuredChannel&&gpa(this,b.featuredChannel,b.annotationId||"branding",
a.videoId||null,a.eventId||null)};
g.h.ac=function(a){a=!a.isCued()&&!g.V(a,1024);g.nK(this.u,a);g.nK(this.A,a)};
g.h.iF=function(a){var b=this.player.getVideoData();b.Gd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),L2(this,b.Gd,a))};
g.h.unload=function(){g.YR(this.player.app,"annotations_module",void 0);g.Ib(this.D,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,v1(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.D={};this.u.hide();g.EQ.prototype.unload.call(this);g.mK(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.EJ=function(a,b,c){this.C=null;!N2(this,b,a)&&(a=g.ip(c)&&c.responseXML?c.responseXML:null)&&(O2(this,a),g.L(this.player.getRootNode(),"iv-module-loaded"))};
g.h.jz=function(a){a==this.player.getVideoData().videoId&&(this.loaded?cpa(this):this.load())};
g.h.ek=function(){return!!this.o&&this.o.isAvailable()};
g.h.Sw=function(){this.ek();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ek();this.o&&(a?c?s2(this.o,c,b):s2(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):t2(this.o))};
g.h.Iq=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.O().D.unsubscribe("vast_info_card_add",this.jz,this);g.dn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.S,b=0,c=a.length;b<c;b++)g.Mo(a[b]);this.S.length=0;g.EQ.prototype.Y.call(this)};g.UQ.annotations_module=I2;g.UQ.creatorendscreen=L1;})(_yt_player);
