(function(g){var window=this;var v5=function(a){g.X.call(this,{F:"button",X:["ytp-offline-slate-button","ytp-button"],K:[{F:"div",I:"ytp-offline-slate-button-icon",W:"{{icon}}"},{F:"div",I:"ytp-offline-slate-button-text",W:"{{text}}"}]});this.C=a;this.A=this.w=null;this.hide();this.ha("click",this.D,this)},x5=function(a,b){!a.w&&b&&b.toggleButtonRenderer?a.w=b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.w=null);
w5(a)},w5=function(a){if(a.w){if(a.w.isToggled){var b=a.w.toggledText?g.qA(a.w.toggledText):"";
a.update({text:b,icon:y5(a.w.toggledIcon)})}else b=a.w.defaultText?g.qA(a.w.defaultText):"",a.update({text:b,icon:y5(a.w.defaultIcon)});a.show()}else a.hide()},y5=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS_NONE":return g.Y?{F:"div",X:["ytp-icon","ytp-icon-notifications-none"]}:{F:"svg",N:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},K:[{F:"path",N:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};case "NOTIFICATIONS_ACTIVE":return g.jN();default:return null}},z5=function(a){g.X.call(this,
{F:"div",
I:"ytp-offline-slate",K:[{F:"div",I:"ytp-offline-slate-bar",K:[{F:"span",I:"ytp-offline-slate-icon",K:[g.Y?{F:"div",X:["ytp-icon","ytp-icon-live-icon"]}:{F:"svg",N:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},K:[{F:"path",N:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{F:"circle",N:{cx:"12",cy:"12",r:"3"}}]}]},{F:"span",I:"ytp-offline-slate-buttons"},{F:"span",I:"ytp-offline-slate-messages",K:[{F:"div",I:"ytp-offline-slate-main-text",W:"{{maintext}}"},{F:"div",I:"ytp-offline-slate-subtitle-text",W:"{{subtitletext}}"}]}]}]});this.A=a;this.B=this.w=null;this.G=!1;this.C=new g.J(this.H,1E3,this);this.M(a,"presentingplayerstatechange",this.J);this.M(a,"livestatedata",this.D);this.hide();a=this.A.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&
this.D(a)},A5=function(a,b,c){if(b){var d=void 0!=b.subtitleText?g.qA(b.subtitleText):"";
b=c?c:void 0!=b.mainText?g.qA(b.mainText):"";a.update({maintext:b,subtitletext:d});g.N(a.element,"ytp-offline-slate-single-text-line",!d)}},E5=function(a){g.EQ.call(this,a);
this.G=!1;this.H=0;this.D=!1;this.o=NaN;this.u=this.w=null;this.B=!1;this.J=new g.nn(1E3,6E4,1);this.S=0;this.A=null;this.L=-(new g.Eg).getTimezoneOffset();this.C=new g.R(this);g.B(this,this.C);var b=this.player.getVideoData(),c=this.player.O();if(!b.sa)!g.S(c.experiments,"html5_release_post_live_heartbeat_killswitch")&&g.Ya(b.Dc,"heartbeat")&&g.lL(this.player,"heartbeat");else if(!g.Cw(c.w))g.LI(this.player.app.w,"html5.unsupportedlive","HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1",void 0);else if(g.S(c.experiments,
"live_fresca_v2")){this.G=this.B=!0;if(!g.Wx(c)||g.gy(c))this.A=new z5(this.player),g.B(this,this.A),g.oL(this.player,this.A.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(this.u=b.playabilityStatus);this.u?(b=B5(this.u.liveStreamability&&this.u.liveStreamability.liveStreamabilityRenderer))?C5(this,b):C5(this,7500):C5(this,1E3)}this.C.M(a,"heartbeatparams",this.sF);this.C.M(a,"presentingplayerstatechange",this.tF);this.C.M(a,"videoplayerreset",this.kM);this.C.M(a,g.kF("heartbeat"),this.rF);
this.B&&this.u&&D5(this,this.u);b=new g.hF(1E3,0x7ffffffffffff,{priority:0,namespace:"heartbeat"});g.kL(a,[b])},Kpa=function(a){var b=a.player.getVideoData();
return!!g.uC(a.player.getVideoData())&&!b.iw},F5=function(a){var b=a.player.getVideoData();
return Kpa(a)?!!a.w:!!b.heartbeatToken},C5=function(a,b){if(!a.o&&a.G){var c=a.player.getVideoData();
if(F5(a)||c.sa)void 0==b&&(b=a.D?a.B?7500:a.w?1E3*a.w.interval:a.player.getVideoData().bw||6E4:1E3),a.o=g.po((0,g.x)(a.eN,a),b)}},D5=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!c.switchStreamsImmediately),e=B5(c),f=a.player.getVideoData();
if(g.vF(g.WK(a.player))&&!g.BC(f)&&!a.player.isAtLiveHead()&&!d)return e;var k=(d=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint)&&d.videoId;if(k)return g.sU(a.player.app,k,void 0,void 0,!0,d),e;if("OK"==b.status.toUpperCase()){d=c&&c.broadcastId;d=d!=(a.u&&a.u.liveStreamability&&a.u.liveStreamability.liveStreamabilityRenderer&&a.u.liveStreamability.liveStreamabilityRenderer.broadcastId)&&(d||a.player.ea("web_player_heartbeat_undefined_killswitch"));if(!f.hlsvp&&!f.Id||d)return c=
{video_id:f.videoId},f.Dm&&(c.is_live_destination="1"),c.autonav_state=f.autonavState,a.player.loadVideoByPlayerVars(c),e;g.lL(a.player,"heartbeat")}c&&c.displayEndscreen&&a.A&&(f=a.A,f.G=!0,f.Ha()&&g.VT(f.A.app,void 0));return e},B5=function(a){var b=0;
a&&a.pollDelayMs&&(a=parseInt(a.pollDelayMs,10))&&(b=a);return b},G5=function(a,b,c){if(a.o){a.o=NaN;
a.H++;var d=a.player.getVideoData();(d.dw||b&&!g.uC(a.player.getVideoData())&&!F5(a)&&d.sa?0:a.H>=(a.w?a.w.o:d.cw||5))?(b=b?"heartbeat.net":"heartbeat.servererror",(d=a.player.getVideoData())&&d.sa?g.LI(a.player.app.w,b,"Video playback interrupted. Please try again.",c,void 0):g.LI(a.player.app.w,b,"Sorry, there was an error licensing this video.",c,void 0)):(C5(a,a.J.getValue()),g.on(a.J))}},H5=function(a){a.H=0;
a.o&&(g.ro(a.o),a.o=NaN);a.D=!1;a.S=0},Lpa=function(a){try{var b=JSON.parse(a);
return null!=b?b:null}catch(c){return null}};
g.r(v5,g.X);
v5.prototype.D=function(){this.A||(this.A=new g.vr(this.C.O().Ba));var a=g.Kq(this.A.o);g.YA()&&(a.context.clientScreenNonce=g.YA());var b;if(this.w.isToggled){if(b=(b=this.w.toggledServiceEndpoint)&&b.removeUpcomingEventReminderEndpoint&&b.removeUpcomingEventReminderEndpoint.params)a.params=b;b="notification/remove_upcoming_event_reminder"}else{if(b=(b=this.w.defaultServiceEndpoint)&&b.addUpcomingEventReminderEndpoint&&b.addUpcomingEventReminderEndpoint.params)a.params=b;b="notification/add_upcoming_event_reminder"}var c={timeout:5E3};
c.onError=(0,g.x)(this.B,this);c.Rd=(0,g.x)(this.B,this);g.Oq(this.A,b,a,c);this.w.isToggled=!this.w.isToggled;w5(this)};
v5.prototype.B=function(){this.w&&(this.w.isToggled=!this.w.isToggled,w5(this))};g.r(z5,g.X);
z5.prototype.D=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.w=a;b=b.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.H():A5(this,b);var c=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail;if(c){for(var d=
0,e=null,f=0;f<c.thumbnails.length;f++)c.thumbnails[f].width>d&&(d=c.thumbnails[f].width,e=c.thumbnails[f].url);e&&(this.element.style.backgroundImage="url("+e+")")}else this.element.style.backgroundImage="";b.actionButtons?(this.B||(this.B=new v5(this.A),this.B.o(this.u["ytp-offline-slate-buttons"]),g.B(this,this.B)),x5(this.B,b.actionButtons[0])):this.B&&x5(this.B,null);this.w=a}else this.w=null;this.J()};
z5.prototype.J=function(){var a=g.WK(this.A),b=this.A.getVideoData(),c=b.sa&&(g.yF(a)||g.V(a,2)||g.V(a,64)),d=2==b.autonavState&&g.V(a,2);a=g.vF(a)&&!g.BC(b)&&!this.A.isAtLiveHead(!0);c&&!a&&!d&&this.w&&"LIVE_STREAM_OFFLINE"==this.w.status.toUpperCase()?this.Ha()||(this.show(),this.A.R("offlineslatestatechange"),this.G&&g.VT(this.A.app,void 0)):this.Ha()&&(this.hide(),this.A.R("offlineslatestatechange"))};
z5.prototype.H=function(){var a=this.w&&this.w.liveStreamability&&this.w.liveStreamability.liveStreamabilityRenderer&&this.w.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.w.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor((0,g.E)()/1E3),c=a.canShowCountdown&&parseInt(a.scheduledStartTime,10);!c||c<=b?(A5(this,a),this.C.stop()):(b=g.OM(c-b),A5(this,a,b),g.Tm(this.C))}};
z5.prototype.Y=function(){this.C.dispose();this.C=null;g.X.prototype.Y.call(this)};g.r(E5,g.EQ);g.h=E5.prototype;g.h.Y=function(){H5(this);g.YR(this.player.app,"heartbeat",void 0);g.EQ.prototype.Y.call(this)};
g.h.rF=function(){this.G=!0;C5(this,2E3)};
g.h.sF=function(a){this.w=a;C5(this,2E3)};
g.h.tF=function(a){g.V(a.state,2)||g.V(a.state,64)?(H5(this),this.B&&(this.G=!0,C5(this,1E3))):(g.V(a.state,1)||g.V(a.state,8))&&C5(this,2E3)};
g.h.kM=function(){3!==this.player.getPresentingPlayerType()&&C5(this,2E3)};
g.h.eN=function(){var a=this.player.O(),b=this.player.getVideoData();var c=a.B;if(3==this.player.getPresentingPlayerType())this.o=NaN;else if(g.V(g.WK(this.player),4))this.o=NaN;else if(F5(this)||b.sa){if(!Kpa(this)||b.sa){var d="GET";var e=a.deviceParams;a={video_id:b.videoId,heartbeat_token:b.heartbeatToken,c:e.c,cver:e.cver,cbrand:e.cbrand,cmodel:e.cmodel,vvt:b.cf,mdx_environment:b.mdxEnvironment,access_token:b.oauthToken,forced_experiments:a.ya,utc_offset_minutes:this.L,upg_content_filter_mode:b.no,
sequence_number:this.S};e=this.player.O();void 0!=e.homeGroupInfo?a.home_group_info=e.homeGroupInfo:void 0!=b.homeGroupInfo&&(a.home_group_info=b.homeGroupInfo);void 0!=e.livingRoomAppMode&&(a.living_room_app_mode=e.livingRoomAppMode);(e="undefined"!=typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)&&(a.time_zone=e);(e=g.qC(b))&&(a.uloc=e);(e=this.player.getProgressState().ingestionTime)&&isFinite(e)&&(a.ingestion_time=e);c=g.Wg(c+"heartbeat",a)}else d="GET",c=g.Wg(this.w.url,
{request_id:g.Cx()}),b.cf&&(c=g.Wg(c,{vvt:b.cf}),b.mdxEnvironment&&(c=g.Wg(c,{mdx_environment:b.mdxEnvironment}))),b.oauthToken&&(c=g.Wg(c,{access_token:b.oauthToken}));b.Rj&&(c=g.Wg(c,{internalipoverride:b.Rj}));a={cpn:b.clientPlaybackNonce};b.contextParams&&(a.context_params=b.contextParams);b.xi&&(a.kpt=b.xi);c=g.Wg(c,a);g.op(c,{format:"RAW",method:d,timeout:3E4,onSuccess:(0,g.x)(this.IE,this),onError:(0,g.x)(this.HE,this),Rd:(0,g.x)(this.JE,this),withCredentials:!0})}else H5(this)};
g.h.IE=function(a){if(this.o){this.J.reset();this.S++;a=a.responseText;var b=Lpa(a);if(b){this.player.ma("onHeartbeat",b);var c="ok"==b.status?b.stop_heartbeat?2:0:"stop"==b.status?1:"live_stream_offline"==b.status?0:-1}else c=(c=a.match(Mpa))?"0"==c[1]?0:1:-1;if(-1==c)b="decode",window.btoa&&(b+=" "+window.btoa(a)),G5(this,!1,b);else if(2!=c||F5(this))if(this.H=0,this.o=NaN,1==c){this.D=!1;b=this.player;c="LICENSE";var d=Lpa(a);d?a=d.reason||g.lJ[c]||"":((a=a.match(Mpa))&&(a=parseInt(a[1],10))&&
(c=g.lF(a)),a=g.lJ[c]||"");g.LI(b.app.w,"heartbeat.stop",a,void 0,void 0)}else this.D=!0,a=0,this.B&&b&&(a=D5(this,b),this.player.R("livestatedata",b)),a?C5(this,a):C5(this);else H5(this),this.D=!0}};
g.h.HE=function(a){G5(this,!0,"net-"+a.status)};
g.h.JE=function(){G5(this,!0,"timeout")};
g.h.qF=function(){return!!this.A&&this.A.Ha()};
var Mpa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.UQ.heartbeat=E5;})(_yt_player);
